### ISSUE TITLE
Trailing zeros on return values

### ISSUE THREAD

**Issue by phemmer** [d4l3k/talib#2]
All of the functions which have a warmup period return trailing zeros.
For example:
```
package main

import (
	"fmt"
	"github.com/d4l3k/talib"
)

func main() {
	in := []float64{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}
	out := talib.Wma(in, 5)
	fmt.Printf("out: ")
	for _, v := range out {
		fmt.Printf(" %.02f", v)
	}
	fmt.Printf("\n")
}
```
```
out:  2.67 3.67 4.67 5.67 6.67 7.67 8.67 9.67 10.67 11.67 12.67 0.00 0.00 0.00 0.00
```

This is happening because some of the variables provided by the C lib aren't being used. The C lib provides `outBegIdx` and `outNBElement` which can be used to trim the trailing data.
For example if we change the `Wma()` function to:
```
func Wma(real []float64, timePeriod int) []float64 {
	var outBegIdx C.int
	var outNBElement C.int
	outReal := make([]float64, len(real))
	C.TA_WMA(0, C.int(len(real)-1), (*C.double)(unsafe.Pointer(&real[0])), C.int(timePeriod), &outBegIdx, &outNBElement, (*C.double)(unsafe.Pointer(&outReal[0])))
	return outReal[:outNBElement] // <- Slice the output
}
```
We now get:
```
out:  2.67 3.67 4.67 5.67 6.67 7.67 8.67 9.67 10.67 11.67 12.67
```

However in addition to using `outNBElement` to slice up `outReal`, the `outBegIdx` should be returned as well so that the caller knows the starting index of `real` for which the first value of `outReal` corresponds to.

**Comment by d4l3k** [comment]
I added the code so it's trimmed to be `outNBElement` length long. I think for the most part `outBegIdx` is inferable based of context so we don't really need the value. Please correct me if I'm wrong.
