### ISSUE TITLE
C int conversion issue

### ISSUE THREAD

**Issue by ColtonProvias** [d4l3k/talib#4]
While Go adapts int to the platform (64-bit systems get int64, while 32-bit systems get int32), C.int is defined as 32 bits. Thus running this library on 64-bit systems gives invalid results when ints are provided. 

A quick test on the MaxIndex function produced the following:

```
253403070522, 266287972412, 270582939710, 287762808899, 287762808899, 335007449166, 335007449166, 335007449166, 335007449166, 335007449166...
```

What was expected was:

```
55, 55, 55, 55, 55, 55, 55, 55, 55, 55...
```

**Comment by d4l3k** [comment]
Ah interesting

**Comment by d4l3k** [comment]
Fixed.
